### ISSUE TITLE
Park feature timer goes too fast

### ISSUE THREAD

**Issue by Portal2Ben** [Flohhhhh/real-brake-lights#4]
Hi, I absolutely love this plug-in, however I did notice that when using the "park" feature sometimes when i come to a stop the vehicle brake lights turn off after only 3-10 seconds instead of the 45-60 that i entered in the config

When pulling a brand new car out, timer is pretty spot on, but as you drive stopping on occasion it seems to go out of sync and starts turning off too fast, would be cool if this feature started the timer once the car came to a stop, and if the car starts going again cancels it till it stops again

Not sure it thats the actual bug, but its definitely something! would love to see this fixed

**Comment by Flohhhhh** [comment]
> would be cool if this feature started the timer once the car came to a stop, and if the car starts going again cancels it till it stops again

This is the intended behavior, if it's not working that way it would be a bug.

Does this happen without changing the config values?

Thanks for creating the issue 😄

**Comment by Flohhhhh** [comment]
Fixed, thanks @Portal2Ben.
If you want to test it, you can pull the main branch instead of downloading the release.

**Comment by Portal2Ben** [comment]
I pulled the main branch and tried but the park feature didn't work whatsoever? 
was enabled in the config with 45 min and 60 max

**Comment by Flohhhhh** [comment]
@Portal2Ben hi I never got the notification for this since the issue was closed, I hope you were able to get it working?

I didn't have any issues in my testing
